### ISSUE TITLE
일정관리 

### ISSUE THREAD

**Issue by hyejungg** [hyejungg/ai-news-noti-bot#10]
# 2.0.0 llm 기반 agent 버전
## 일정
**~11/4(월)**
- [x] molly : #45 (news-agent 폴더 내에 프로젝트 초기 세팅하기)
- [x] justin : #49

**~11/7(목)**
- 회의
- [x] justin : #59 
- [x] molly : #55 

**~11/18(화)**
- [x] justin : #56 + 추가 코드리뷰 반영
- [x] molly : #50 + 결과 확인해보고 공유하기

**~11/26(화)**
- [x] justin : #66 + 중복 메시지 제거
- [x] molly : #52 

**~11/29(금)**
- [x] justin : #70
- [x] molly : #52 

**~12/5(목)**
- 목요일 전에 공유할 내용 있으면 언제든지 하기!
- [x] justin : #69 
- [x] justin : #71
- [x] molly : #58 
    - news-scraper-agent 파이썬 앱을 lambda 로 올리도록 전환하기 (temlate.yaml, sam config ...)
- [x] justin: #81 
- [x] justin : #87 
- [x] molly : #86 

**12/9(월)~12/11(수)**
- [x] 발표준비 ^~^

**~12/13(금)**
- [x] 발표 ^~^

## 참고사항
**- 11월 말에는 끝내자!!!!!** 

### 추후에
- [x] #53 
- [ ] 새해부터 새버전으로 배포해두기

---

# 1.0.0-archive
## 일정
**3/12 (화) -> 3/14 (목)**
- [x] molly : 미리 aws 계정 만들어두기
- [x] 같이 : iam 계정 생성하고 lambda 권한 설정

**3/15 (금) ~ 3/17 (일)**
- [x] molly : #5
- [x] justin : #9 
- [x] justin : #11 

**3/18 (월) ~ 3/25 (월)** 
- [x] molly : #12, #13
- [x] molly : #18
- [x] justin : #15, #19

**3/26 (화)**
- [x] ppt 작성

### 미정
- https://rapidapi.com/everyday/api/ai10 이용해서 뉴스 정보 가져오기
- 크롤링 자동화 with llm
- 사이트별로 람다 구성
  - 사이트별 크롤링 -> 병렬로 구성
  - 결과를 메시지로 가공하는 부분을 하나로 받아서 해
  - 그렇지만 공통 코드가 존재하는 문제가 있음
  - 또 도커 파일도 여러개 존재하는 문제가 있음

**3/27 (수)**
- 발표 자료 피드백 및 수정

**3/28 (목)** 
- 프로젝트 발표 !! 두둥다당

## 참고사항
- 3/25~26 저스틴 휴가

**Comment by hyejungg** [comment]
AWS 에서 프로젝트 관련 설정 시 태그 값 지정하기
- key : `PROJECT`
- value : `AI_NEWS_NOTI_BOT`

**Comment by hyejungg** [comment]
### 발표 메모

알게된 사실
- 그래프 내 시퀀스 내 에이전트에서 예외 처리 하는거 고민했음 (실제로 발생해가지고) 
  - 일부 에이전트에서 예외 발생 시 exception을 catch 해서 빈 응답으로 다음 에이전트로 넘겨서 시퀀스를 skip되도록 구현 
- `self.llm.with_structured_output(AgentResponse)`
   - 이거쓰면 내가 정의한 class 타입에 맞게 응답을 준다.  (json_ouput_parser 필요 없음)
- 4o-mini는 뭘 못하는데 4o는 . 뭘잘해서 4o로 했다. (PR에 있음)
   - 4o-mini는 크롤링 내용 뽑아올 때 title은 못뽑아오거나 못하고
   - 요청한대로 json 대로 안만드는 ...  
   - https://github.com/hyejungg/ai-news-noti-bot/pull/72
   - https://github.com/hyejungg/ai-news-noti-bot/pull/68
- 현재 1회 0.09 달러 정도 발생 -> 2일일 실행된다고 하면 한달에 1.8$ 발생 에정 -> 최적화 예정임
